### ISSUE TITLE
Packaging this for NixOS

### ISSUE THREAD

**Issue by CMCDragonkai** [GarCoSim/TraceFileGen#6]
I'm packaging this for NixOS.

Does this package have a "version"? Currently, I'm assuming a rolling release. So I'm using just your latest git revision.

Also can you please change `/bin/bash` to `/usr/bin/env bash`? Or just `/usr/bin/env sh`. On NixOS, `/bin/bash` doesn't exist.

**Comment by JohnnyTriangles** [comment]
I've made the script change that you've suggested, and I can confirm that the package is on a rolling release. Thank you for your input.
